// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {main} from '../models';

export function LoadSettings():Promise<settings.Settings>;

export function OpenFileDialog():Promise<main.FileContent>;

export function ParseMarkdown(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
